-- Tandem — the whole backend, in one file.
--
-- Paste this into the Supabase SQL editor and run it once. It creates the
-- tables, locks them down, and wires up the two-seat invite system.
--
-- The security model in one line: two people who chose each other can see
-- everything, but only you can claim you did your own work.

-- ---------------------------------------------------------------- seats
-- Exactly who is allowed in. Anyone who signs up with an email that is not
-- listed here gets an account with no membership, and every policy below
-- denies them, so they see an empty app and a "no seat" notice.

create table if not exists seats (
  email        text primary key,
  role         text not null default 'student',   -- 'student' | 'partner'
  display_name text not null default ''
);

-- ---------------------------------------------------------------- members

create table if not exists members (
  id           uuid primary key references auth.users on delete cascade,
  email        text not null,
  display_name text not null default '',
  role         text not null default 'student',
  prefs        jsonb not null default '{}'::jsonb,   -- every UI preference
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Membership is what every other policy hangs off. SECURITY DEFINER so the
-- check itself is not subject to the policies it is being used to evaluate.
create or replace function is_member() returns boolean
  language sql stable security definer set search_path = public as $$
  select exists (select 1 from members where id = auth.uid());
$$;

-- A new signup claims its seat, or gets nothing.
create or replace function handle_new_user() returns trigger
  language plpgsql security definer set search_path = public, auth as $$
declare s public.seats%rowtype;
begin
  select * into s from public.seats where lower(email) = lower(new.email);
  if not found then
    return new;                      -- no seat: account exists, sees nothing
  end if;
  insert into public.members (id, email, display_name, role)
  values (new.id, new.email,
          coalesce(nullif(s.display_name, ''), split_part(new.email, '@', 1)),
          s.role)
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function handle_new_user();

-- ---------------------------------------------------------------- content
-- Ids are generated by the browser so a write works offline and syncs later
-- without ever colliding. owner_id is whose life the row is about.

create table if not exists subjects (
  id        uuid primary key,
  owner_id  uuid not null references members(id) on delete cascade,
  code      text not null,
  name      text not null default '',
  color     text not null default '',
  position  int  not null default 0,
  archived  boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists lessons (
  id         uuid primary key,
  owner_id   uuid not null references members(id) on delete cascade,
  subject_id uuid references subjects(id) on delete cascade,
  dow        int  not null,             -- 0 = Monday
  period     int  not null,
  start_min  int  not null,             -- minutes from midnight
  end_min    int  not null,
  title      text not null default '',
  room       text not null default '',
  teacher    text not null default '',
  updated_at timestamptz not null default now()
);

-- One tick per subject per school day. Its absence is what carries homework
-- forward to the next day.
create table if not exists hw_checks (
  id         uuid primary key,
  owner_id   uuid not null references members(id) on delete cascade,
  subject_id uuid not null references subjects(id) on delete cascade,
  date       date not null,             -- the day the homework was set
  done_at    timestamptz not null default now(),   -- when you actually did it
  updated_at timestamptz not null default now(),
  unique (owner_id, subject_id, date)
);

create table if not exists tasks (
  id          uuid primary key,
  owner_id    uuid not null references members(id) on delete cascade,
  subject_id  uuid references subjects(id) on delete set null,
  title       text not null,
  notes       text not null default '',
  due_date    date,
  priority    int  not null default 1,  -- 0 low, 1 normal, 2 high
  est_minutes int  not null default 30,
  done        boolean not null default false,
  done_at     timestamptz,
  created_by  uuid references members(id) on delete set null,
  position    int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists goals (
  id         uuid primary key,
  owner_id   uuid not null references members(id) on delete cascade,
  title      text not null,
  detail     text not null default '',
  kind       text not null default 'count',    -- count | minutes | percent | habit
  target     numeric not null default 1,
  unit       text not null default '',
  cadence    text not null default 'once',     -- once | daily | weekly | monthly
  start_date date not null default current_date,
  due_date   date,
  color      text not null default '',
  pinned     boolean not null default false,
  archived   boolean not null default false,
  created_by uuid references members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Progress is a log, never a single number, so the chart and the streak are
-- both derivable and nothing can silently overwrite history.
create table if not exists goal_log (
  id         uuid primary key,
  goal_id    uuid not null references goals(id) on delete cascade,
  owner_id   uuid not null references members(id) on delete cascade,
  amount     numeric not null default 1,
  note       text not null default '',
  date       date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- How the two of you talk to each other inside the app.
create table if not exists notes (
  id         uuid primary key,
  author_id  uuid not null references members(id) on delete cascade,
  target_id  uuid not null references members(id) on delete cascade,
  body       text not null,
  kind       text not null default 'note',   -- note | nudge | praise
  ref_table  text not null default '',
  ref_id     uuid,
  read_at    timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists xp_events (
  id         uuid primary key,
  owner_id   uuid not null references members(id) on delete cascade,
  source     text not null,
  amount     int  not null,
  note       text not null default '',
  day        date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_checks_owner_date on hw_checks(owner_id, date);
create index if not exists idx_tasks_owner       on tasks(owner_id, done);
create index if not exists idx_goallog_goal      on goal_log(goal_id, date);
create index if not exists idx_xp_owner_day      on xp_events(owner_id, day);
create index if not exists idx_notes_target      on notes(target_id, created_at desc);

-- updated_at is what the sync polls on, so it must never be client-supplied.
create or replace function touch_updated_at() returns trigger
  language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['members','subjects','lessons','hw_checks','tasks',
                           'goals','goal_log','notes','xp_events'] loop
    execute format('drop trigger if exists touch_%1$s on %1$I', t);
    execute format('create trigger touch_%1$s before update on %1$I
                    for each row execute function touch_updated_at()', t);
  end loop;
end $$;

-- ------------------------------------------------------------------- rls

alter table seats     enable row level security;
alter table members   enable row level security;
alter table subjects  enable row level security;
alter table lessons   enable row level security;
alter table hw_checks enable row level security;
alter table tasks     enable row level security;
alter table goals     enable row level security;
alter table goal_log  enable row level security;
alter table notes     enable row level security;
alter table xp_events enable row level security;

-- seats: readable by members so the app can show who is invited. Never
-- writable from the browser — you add seats in the SQL editor.
drop policy if exists seats_read on seats;
create policy seats_read on seats for select using (is_member());

-- members: both of you can see each other. You can only edit yourself, so
-- neither can change the other's role, name, or preferences.
drop policy if exists members_read on members;
drop policy if exists members_self on members;
create policy members_read on members for select using (is_member());
create policy members_self on members for update using (id = auth.uid())
  with check (id = auth.uid());

-- Shared, but only you can claim your own work.
-- hw_checks, goal_log and xp_events are the record of what YOU did, so they
-- are writable only by their owner. Everything else either of you can edit,
-- which is what lets your partner set goals and write tasks for you.
do $$
declare t text;
begin
  foreach t in array array['subjects','lessons','tasks','goals'] loop
    execute format('drop policy if exists %1$s_all on %1$I', t);
    execute format('create policy %1$s_all on %1$I for all
                    using (is_member()) with check (is_member())', t);
  end loop;

  foreach t in array array['hw_checks','goal_log','xp_events'] loop
    execute format('drop policy if exists %1$s_read on %1$I', t);
    execute format('drop policy if exists %1$s_own on %1$I', t);
    execute format('create policy %1$s_read on %1$I for select using (is_member())', t);
    execute format('create policy %1$s_own on %1$I for all
                    using (owner_id = auth.uid()) with check (owner_id = auth.uid())', t);
  end loop;
end $$;

-- notes: you write as yourself; the person it is addressed to may mark it read.
drop policy if exists notes_read on notes;
drop policy if exists notes_write on notes;
drop policy if exists notes_mark on notes;
create policy notes_read  on notes for select using (is_member());
create policy notes_write on notes for all
  using (author_id = auth.uid()) with check (author_id = auth.uid());
create policy notes_mark  on notes for update
  using (target_id = auth.uid()) with check (target_id = auth.uid());
